<a href="https://colab.research.google.com/github/franceslawley/Python_Skills/blob/main/2_Pandas_and_Numpy_Packages.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
import pandas as pd
import numpy as np

data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [2, 1, 1, 2, 2, 4, 1]}

#Q1-1: create dataframe from data (used pandas because multiple data types)
dataframe = pd.DataFrame(data, columns = ['name', 'job', 'family_size', 'num_cars'])
print(dataframe)

     name                 job  family_size  num_cars
0  Joseph             teacher            3         2
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1


In [ ]:
#Q1-2: select psychologists or teachers and number of cars > family size
dataframe[(np.logical_or(dataframe.job=='psychologist', dataframe.job=='teacher'))&(dataframe.num_cars > dataframe.family_size)]

name           job  family_size  num_cars
5  Lisa  psychologist            3         4

In [ ]:
#Q1-3:  Select people who have at most 2 family members and at least 1 car
print(dataframe[(dataframe.family_size<=2) & (dataframe.num_cars>=1)])

    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1


In [ ]:
#Q1-4: Write a code that get number of unique jobs in this dataset.
print(dataframe['job'].unique())

['teacher' 'psychologist' 'data scientist' 'software developer']


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
import pandas as pd
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
print(fruit)

weights = pd.Series(np.linspace(1, 10, 10)) #Linspace is used to create an evenly spaced sequence in a specified interval
print(weights)

data = {"fruit":fruit, "weights":weights} #put data into dictionary 
#series = pd.concat([fruit,weights],axis=1)
series = pd.concat(data, axis = 1) #arrange data into dataframe
print(series)

In [ ]:
series = pd.concat([fruit,weights],axis=1)
print(series)

In [ ]:
# Type your solution here

print("Apple Average:", np.mean(weights[series.fruit =='apple']))
print("Banana Average:",np.mean(weights[series.fruit =='banana']))
print("Carrot Average:",np.mean(weights[series.fruit =='carrot']))

Apple Average: 3.0
Banana Average: 4.0
Carrot Average: 7.2


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])
sorted = np.sort(course_name) #sort in alphabetical order
print(sorted)

['JS' 'PHP' 'Python' 'examples' 'html']


In [ ]:
#Q3-1
print(course_name.argsort()) #indexes 

#print(sorted.argsort()) #indexes with sorted list by alphabetical order

[1 3 0 2 4]


In [ ]:
#Q3-2
for element in sorted:
  if element[:][0] == 'P': #if the first letter in each element =='P'
    print(element, "starts with a P!")
  else:
    print(element, "doesn't start with P!")

JS doesn't start with P!
PHP starts with a P!
Python starts with a P!
examples doesn't start with P!
html doesn't start with P!


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

#Q4-1
print(student_id) #original
print(student_id[::-1]) #reversed

#Q4-2
sorted = np.sort(student_id) #sort
print(sorted[::-1][0:3]) #select top 3 largest values (first 3 values in descending sorted array)

[1023 5202 6230 1671 1682 5241 4532]
[4532 5241 1682 1671 6230 5202 1023]
[6230 5241 5202]


In [ ]:
#Q4-2
sorted = np.sort(student_id) #sort
print(sorted[::-1][0:3]) #select top 3 largest values (first 3 values in descending sorted array)

**Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 

---

100**

In [ ]:
def multiple():

  multiples =[]
  sum = 0
  value_list = list(range(1,100)) #create range of numbers 0 - 100
  print(value_list)

  for e in value_list:
    if e % 3 == 0 or e % 5 == 0: #if number is divisable by 3 or 5 (multiple)
      multiples.append(e)        
      sum = sum + e              
  print(sum)                     
  print(multiples)              

multiple() #this is correct!

**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4) #creates n dimensional array 
print(arr)

#Q6-1
arr[:, [0,1]] = arr[:, [1,0]]
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]]


In [ ]:
#Q6-2
#arr = np.arange(12).reshape(3,4) #creates n dimensional array 
arr[[0,1], :] = arr[[1,0], :]
print(arr)

[[ 5  4  6  7]
 [ 1  0  2  3]
 [ 9  8 10 11]]
